### PR TITLE
Document extended assertions

### PR DESCRIPTION
**Pull request by alexjeffburke**
Hey,

See what you think of this - I added some documentation about the extended assertions. Now I've done it I realise I've mixed in some other changes here too.. if you'd prefer I take those out just shout :)

AJB

### CODE REVIEW

**Comment by sunesimonsen** [comment]
It is probably a good idea to mention http://unexpectedjs.github.io/api/addAssertion/ if we don't already.

**Comment by alexjeffburke** [comment]
There was an example in the docs already using a custom assertion - I hoped to make it even clearer with the addition of an obvious section title for it in the first of the commits :) But perhaps it's worth adding a link to those docs too?

**Comment by alexjeffburke** [comment]
Ugh that's what happens when you rush to get something done :) Thanks for the review, I'll force push with a fixup tomorrow morning!

**Comment by papandreou** [comment]
Thanks a lot for the contribution! Certainly a nice improvement.

Would be great having the link now that we finally have something to link to.

**Comment by alexjeffburke** [comment]
I've just forced push this with the corrections and an additional link to the unexpected addAssertion documentation :)

**Comment by papandreou** [comment]
Thanks a lot!

**Pull request merged**
